### ISSUE TITLE
Misc build failures due to inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [mvoidex/simple-log#4]
Similiar to https://github.com/mvoidex/hformat/issues/2 I found inaccurate version bounds in `simple-log` (see screenshots below)

I've already fixed up the incorrect metadata via revisions for the affected releases:

 - https://hackage.haskell.org/package/simple-log-0.7.0/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.0/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.1/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.2/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.3/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.4/revisions/
 - https://hackage.haskell.org/package/simple-log-0.8.5/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.0/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.1/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.2/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.3/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.4/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.5/revisions/
 - https://hackage.haskell.org/package/simple-log-0.9.6/revisions/

you can review the latest buildreport at https://matrix.hackage.haskell.org/package/simple-log

If you're intentionally dropping support for base-4.8, please make sure that future releases of `hformat` have `base >= 4.9` as lower bound; if instead you want to restore compatibility w/ GHC 7.10.3 & base-4.8, you can add a conditional dependency such as

```
  if !impl(ghc >= 8.0)
     build-depends: semigroups >= 0.18.2 && < 0.19
```

(but this probably only makes sense if done also for `hformat`) to your `.cabal` file.

Please consider using something like https://github.com/haskell-CI/haskell-ci to help detect such issues in future.

Again, if you have any questions please let me know!

----

![](https://user-images.githubusercontent.com/285533/44514947-a1e77680-a6c1-11e8-9ee5-e750660463b2.png)

----

![](https://user-images.githubusercontent.com/285533/44514957-a90e8480-a6c1-11e8-9c66-d2a7d303ca04.png)

**Comment by mvoidex** [comment]
Thanks! Uploaded 0.9.7, added ghc-7.10.3 to travis
